"""update

Revision ID: 35ed5f4d13c8
Revises: a7936e341059
Create Date: 2025-06-19 23:13:52.005677

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "35ed5f4d13c8"
down_revision: Union[str, Sequence[str], None] = "a7936e341059"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
