"""initial

Revision ID: b693178ffef1
Revises: 84319ed0bb57
Create Date: 2025-06-19 23:07:05.739128

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b693178ffef1"
down_revision: Union[str, Sequence[str], None] = "84319ed0bb57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
