"""initial

Revision ID: c3f51f87a6d9
Revises: b693178ffef1
Create Date: 2025-06-19 23:07:57.871632

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c3f51f87a6d9"
down_revision: Union[str, Sequence[str], None] = "b693178ffef1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
